import time, pyautogui
print("Starts in 3 seconds. Please focus Discord and select the text box.")
time.sleep(3)
print("Starting now, please leave your computer on and Discord open.")
x = 45
def dankbeg():
    pyautogui.write("pls beg")
    pyautogui.press('enter')
def dankdig():
    pyautogui.write("pls dig")
    pyautogui.press('enter')
def dankfish():
    pyautogui.write("pls fish")
    pyautogui.press('enter')
def dankhunt():
    pyautogui.write("pls hunt")
    pyautogui.press('enter')
def countdown():
    time.sleep(1)
    print("44")
    time.sleep(1)
    print("43")
    time.sleep(1)
    print("42")
    time.sleep(1)
    print("41")
    time.sleep(1)
    print("40")
    time.sleep(1)
    print("39")
    time.sleep(1)
    print("38")
    time.sleep(1)
    print("37")
    time.sleep(1)
    print("36")
    time.sleep(1)
    print("35")
    time.sleep(1)
    print("34")
    time.sleep(1)
    print("33")
    time.sleep(1)
    print("32")
    time.sleep(1)
    print("31")
    time.sleep(1)
    print("30")
    time.sleep(1)
    print("29")
    time.sleep(1)
    print("28")
    time.sleep(1)
    print("27")
    time.sleep(1)
    print("26")
    time.sleep(1)
    print("25")
    time.sleep(1)
    print("24")
    time.sleep(1)
    print("23")
    time.sleep(1)
    print("22")
    time.sleep(1)
    print("21")
    time.sleep(1)
    print("20")
    time.sleep(1)
    print("19")
    time.sleep(1)
    print("18")
    time.sleep(1)
    print("17")
    time.sleep(1)
    print("16")
    time.sleep(1)
    print("15")
    time.sleep(1)
    print("14")
    time.sleep(1)
    print("13")
    time.sleep(1)
    print("12")
    time.sleep(1)
    print("11")
    time.sleep(1)
    print("10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
if __name__ == '__main__':
    count = 0
    while 0 < 5:
       dankbeg()
       dankdig()
       dankfish()
       dankhunt()
       countdown()